name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      DEPLOYMENT_NAME: Development
      GIT_COMMIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3

      - name: Install dependencies
        run: npm i
        working-directory: .

#      - name: Test
#        run: npm run test --ci --coverage
#        working-directory: .

      - name: Build
        run: npm run build
        working-directory: .

#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: caodam2504/sandbox-app
#          tag_with_ref: true

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Build the Docker image
      - name: Build Image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GIT_COMMIT_HASH" \
            .
      # Push the Docker image to Google Container Registry
      - name: Push image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_COMMIT_HASH"

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      # Deploy the Docker image to the GKE cluster

      - name: Deploy Docker image to cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide

