name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3

      - name: Install dependencies
        run: npm i
        working-directory: .

#      - name: Test
#        run: npm run test --ci --coverage
#        working-directory: .

      - name: Build
        run: npm run build
        working-directory: .

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: caodam2504/sandbox-app
          tag_with_ref: true

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |-
          docker build --build-arg -t gcr.io/$PROJECT_ID

      - name: Configure Docker to use gcloud cli as a credential helper
        run: |
          gcloud auth configure-docker -q

      - name: Push to GCR
        run: |-
          docker push gcr.io/$PROJECT_ID

